

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";


export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL";


export const ADJUST_CART_QTY_REQUEST = "ADJUST_CART_QTY_REQUEST";
export const ADJUST_CART_QTY_SUCCESS = "ADJUST_CART_QTY_SUCCESS";
export const ADJUST_CART_QTY_FAIL = "ADJUST_CART_QTY_FAIL";


export const CLEAR_SUCCESS = "CLEAR_SUCCESS"
export const CLEAR_ERROR = "CLEAR_ERROR"

